---
title: "Gapminder"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gather data

```{r}
download.file(url = "https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes_rmd/data/gapminder_data.csv", destfile = "data/gapminder_data.csv")
gapminder <- read.csv("data/gapminder_data.csv")
```
```{r}
getwd()
```

```{r}
head(gapminder)
```
## Plotting Data

```{r}
library(ggplot2)
```

### How does life expectancy change with GDP per capita?

```{r}
ggplot(data = gapminder, mapping = aes(x=gdpPercap, y=lifeExp)) + 
  geom_point(size=1, alpha=0.25) +
  scale_x_log10() +
  geom_smooth(method="lm", size=1.5)
```

### How does life expectancy change per year?

```{r}
ggplot(data = gapminder, mapping = aes(x=year, y=lifeExp, by=country)) + 
  geom_line(mapping = aes(color=continent)) +
  geom_point()
```

###How does life expectancy change per year in the Americas?

```{r}
americas <- gapminder[gapminder$continent =="Americas", ]
ggplot(data = americas, mapping = aes(x=year, y=lifeExp, color=country)) +
  geom_line()
```

```{r}

ggplot(data = americas, mapping = aes(x=year, y=lifeExp)) + 
  geom_line() +
  facet_wrap(~country) +
  theme(axis.text.x = element_text(angle=90))
```

```{r}
lifeExp_plot <- ggplot(data = americas, mapping = aes(x=year, y=lifeExp)) + 
  geom_line() +
  facet_wrap(~country) +
  theme(axis.text.x = element_text(angle=90))
```

```{r}
lifeExp_plot
ggsave(plot=lifeExp_plot, filename = "lifeExp.png")
```
